# Variables
@baseUrl = http://localhost:3333

###

# Health check
GET {{baseUrl}}/health

###

# @name register
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "password": "123456",
  "passwordConfirmation": "123456"
}

###

# @name auth
POST {{baseUrl}}/auth
Content-Type: application/json
Authorization: Bearer {{register.response.body.token}}

{
  "email": "johndoe@example.com",
  "password": "123456"
}
